### PR TITLE
Streamline build commands and fix GitHub Actions

### PR DESCRIPTION
**Pull request by alecananian**
Fixes the GitHub Actions workflow by streamlining the build commands and ensuring each workspace has the same commands defined

### CODE REVIEW

**Comment by wyze** [comment]
I will need to fix and merge #2 before this as I don't want this to deploy to production over what we currently have deployed for Bridgeworld.

**Comment by alecananian** [comment]
Should we delete the root `/tests` folder with this PR as well?

**Comment by wyze** [comment]
> Should we delete the root `/tests` folder with this PR as well?

Yes, they serve no purpose here. Was just left over from copy and paste.

**Review by wyze — CHANGES_REQUESTED** [review]
@alecananian Can you merge latest master in and remove the root `tests/` folder as discussed in Discord.

**Comment by alecananian** [comment]
@wyze can do! However, the `codegen` command is failing for the `marketplace` subgraph because a lot of contracts are missing from the testnet config (the smol projects, marketplace, etc). Do you have those configs? Or should we disable the dev deploy of the `marketplace` subgraph for now?

**Comment by alecananian** [comment]
Those new legions tests are failing though - same thing happening on my local setup. Looks like the `Token` store does not have the expected token IDs loaded in it.

**Review by wyze — APPROVED** [review]

**Comment by wyze** [comment]
Awesome work @alecananian!

**Pull request merged**
